# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be5c1ea3109d8bbc155ede8e1c2eddf1f5e6467814af67fab37bbf1ef03ba4fe3152b0b519871e3cb1ffbde6e7551674e1ed5246ad9c6a93f8a96c40aa3c66e2

test:
  secret_key_base: 6c7aea2b5adb858dce1d3b5c6828218ed0e82700273ef88f59db4a7a22e94ebacc720771c955e26d05d97dd23c88f23f97e694eb39452848a5d8467e40950240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
